### ISSUE TITLE
为什么 adminApp 是新建一个 express 的实例而不是使用 router?

### ISSUE THREAD

**Issue by IchiNiNiIchi** [chickencyj/blog-by-nodejs#1]
RT

**Comment by chickencyj** [comment]
你说的是express.Router()吧？因为在configs里我还要对具体控制模块进行进一步划分，而在控制每个具体路由的时候才使用express.Router()，这个在controller目录里

**Comment by IchiNiNiIchi** [comment]
cnodejs 对模块划分应该也有需求，粗略看了下也只是用到 Router,  所以有这个疑问

**Comment by chickencyj** [comment]
我还没看过cnodejs源码，有时间会去看看学习下
